### ISSUE TITLE
`depth` option does not work

### ISSUE THREAD

**Issue by saadtazi** [AceMetrix/npm-license#12]
In the README, there is an example of a command that uses the `depth` option: `npm-license --depth=3`

But I get the following error when running that exact same command (node 0.10.33, npm 2.1.11):

```
npm-license --depth=1 > licenses.txt

/home/XXX/.nvm/v0.10.33/lib/node_modules/npm-license/node_modules/nopt-usage/index.js:10
    var option = value.replace('--', '');
                       ^
TypeError: Object #<Object> has no method 'replace'
    at /home/XXX/.nvm/v0.10.33/lib/node_modules/npm-license/node_modules/nopt-usage/index.js:10:24
    at Array.forEach (native)
    at showUsage (/home/XXX/.nvm/v0.10.33/lib/node_modules/npm-license/node_modules/nopt-usage/index.js:8:27)
    at Object.usage (/home/XXX/.nvm/v0.10.33/lib/node_modules/npm-license/lib/args.js:42:12)
    at Object.<anonymous> (/home/XXX/.nvm/v0.10.33/lib/node_modules/npm-license/bin/npm-license:12:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by anacronw** [comment]
That's interesting, I just tried it myself.

I suspect there's a specific dependency that may be causing that problem

**Comment by saadtazi** [comment]
I agree: I opened that issue 5 years ago. I reinstalled this exension globally (new computer, new node version, new npm...), with node v13.8.0, I confirmed that it worked.
